# Generated by Django 5.2.3 on 2025-07-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.TextField(verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.IntegerField(verbose_name='ID объекта'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_type',
            field=models.CharField(max_length=50, verbose_name='Тип объекта'),
        ),
    ]
